export { default as Hamburger } from './Hamburger';
export { default as Header } from './Header';
export { default as Menu } from './Menu';
export { default as LoginMenu } from './LoginMenu';
export { default as ErrorPage } from './ErrorPage';
export { default as Registration } from './Registration';
export { default as FindRestaurant } from './FindRestauration';
export { default as Box } from './Box';
export { default as MainPage } from './MainPage';
